### ISSUE TITLE
Incorrect audio playback at too low and too high volume

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#13]
When you listen to any kind of audio through the speaker / headphone at a too high or too low volume, the sound becomes either terribly loud and wrong or too quiet. In any case, there is interference in the audio. There is no proper sound balance. We need good audio performance. We need perfect audio.

**Comment by shakalaca** [comment]
I'm not familiar with audio, any ideas ? :)

**Comment by sultan2304** [comment]
Fixed
