### ISSUE TITLE
For a what there is a Asus FlipCover app?

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#17]
In my humble opinion, we don't need this system app because of its irrelevance and errors. As for the people who need this app, they can install it using the .zip archive. Can you make the .zip of Asus FlipCover and remove it from system apps?

**Comment by shakalaca** [comment]
The purpose of this wrapper is:
1. Entry point of settings
2. Some people want to use flipcover without ASUS Flip Cover app, but with "config_lidControlsSleep" set to "true" the ASUS Flip Cover app won't work. For one build to compatible with both needs we have to build another app to handle those case.

**Comment by sultan2304** [comment]
Won't you delete this app from system apps? If we want to become official supported device, we need to remove this app and any connected code..
It will make our build more stable.

**Comment by shakalaca** [comment]
@sultan2304 If you're willing to be the maintainer, just fork and do whatever you like, I'm happy to see someone with passion taking over this project :)

**Comment by sultan2304** [comment]
@shakalaca Okay. Thanks. Can you fix FlipCover errors?

**Comment by nerthazrim** [comment]
Thanks a lot for your work!

@shakalaca I do have a FlipCover and it works almost perfectly, it is wasn't for the regular crashes that the app does :(

Sometimes the app even crashes when the FlipCover is closed (and the "flip mode" is enabled), locking the phone on the "flip screen". Sometimes the "flipscreen" won't appear at all when the Cover has been closed.

Any help? Could you fix that? :)

Thanks!
