### ISSUE TITLE
Doze mode doesn't work well

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#18]
Battery performance is terrible! I have 5 hours of display on. By the way, I had more than 7 hours before. What is it? Please, fix the doze mode!

**Comment by shakalaca** [comment]
I'm not familiar with doze mode, any ideas ? :)

**Comment by Planet-X** [comment]
Doze mode surely is not to blame here - the android doze feature only kicks in if the device is really in idle (screen off, not moving). This means doze can only improve screen off battery time.
@sultan2304 As a first step of finding the issue you could try running `powertop` **as root** from a terminal emulator or adb shell. This application shows information about current cpu usage, C- and P-States. It also shows which currently running processes/interrupts wake up your processor from idle the most. Maybe you can identify the process that takes all your battery life.
