### ISSUE TITLE
Can't choose "Vivid" mode in Asus Splendid

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#21]
There is a small bug in 30.07 version of build. I can't open the Asus Splendid because there is no notification in the notification bar. I need to turn on Vivid mode, but I can't.  Can you fix it, shakalaca? Maybe you can add Vivid mode option to the toggle in the notification bar? (there are only two options: 1) blue filter 2) balance mode)

**Comment by sultan2304** [comment]
Shakalaca, can you add Asus Splendid notifications, please?

**Comment by tuanpq1998** [comment]
Hi sultan, I made some changes to enable Splendid to show in app drawer. You can flash it via TWRP, afer that you can set notification on or turn to Vivid mode https://drive.google.com/open?id=0B649GK1qdCxrOC1rcXNoakZTcXc

**Comment by sultan2304** [comment]
@rororo1235 thanks a lot bro! It works perfectly

**Comment by shakalaca** [comment]
@rororo1235 you rocks ! :)

**Comment by sultan2304** [comment]
@shakalaca yup :)
