### ISSUE TITLE
Cant use AsusCamera

### ISSUE THREAD

**Issue by tuanpq1998** [shakalaca/android_device_asus_ze520kl#22]
Cant capture using asus camera, error "Operation failed. Insert a memory card and try again"
If I remove 'ro.sys.sdcardfs=true' from build.prop, everthing works fine

**Comment by shakalaca** [comment]
Side effect when enabling sdcardfs, should be fixed: https://github.com/shakalaca/android_device_asus_Z017/commit/1e26caeda5eb55ba94743914d8e2606035c016af
