### ISSUE TITLE
Lineage Camera crashes on launch on 20170730 build

### ISSUE THREAD

**Issue by nerthazrim** [shakalaca/android_device_asus_ze520kl#23]
Hi,

After updating Lineage with the 20170730 build (even the patched one), the built-in Camera app' is crashing on launch :(

Any fix planned? :)

Thanks!

**Comment by shakalaca** [comment]
hmm.. works on my phone, I'll do a clean install and try again later.

**Comment by nerthazrim** [comment]
I just tried again, here is what I did:

I started from the 20170706 build, where the Lineage Camera app is working fine and the Asus Camera downloaded from the Store works well, except that it doesn't want to switch to the microSD card to store the images.

I flashed the phone with the 20170730 build (noSU patch) and the Lineage Camera app is not starting at all (crash at startup) and the Asus Camera says that "There is no external storage available", something like that, even with the Internal Storage selected.
The Asus Camera issue is probably linked to this one: https://github.com/shakalaca/android_device_asus_Z017/issues/22 ?

When reverting back to 20170706, back to the status above.

Additionnal question for you: is there any reason to use the AsusCamera.zip file that you give on your Mega storage space instead of the Asus Camera available on the Play Store?

Thanks!

**Comment by tuanpq1998** [comment]
Shakalaca fixed this bug, see #22
About your question: You should use the zip file because it was taken from stock firmware of zenfone 3, it had HDR auto function, manual mode had more features than the one on store,...
https://drive.google.com/open?id=0B649GK1qdCxrNlhDV0ZKd2l2NFU 
I took it from newest firmware :) newest camera and Gallery, you can use this file.
@shakalaca can you replace the old AsusCamera.zip on your mega link with this one?

**Comment by nerthazrim** [comment]
@rororo1235 thanks for the explanation!

So! I reflashed with the 20170730 build and added your AsusCamera ZIP (I deleted the store app first).

I can confirm that the Lineage Camera App is still there: crash at startup. The Asus app however is working perfectly! I can save on the microSD too.

Thanks!

Still, it might be good to fix this bug if somebody prefers the Lineage app.

**Comment by nerthazrim** [comment]
@shakalaca hey! Out of the blue, the Asus Camera app' is not working anymore...

When I take a picture, the preview appears in the bottom right corner but if I click on it, the app freezes. No picture is saved on the filesystem, either internal or external SD card :(
I can take pictures with other apps such as Whatsapp or Signal though.
