### ISSUE TITLE
Speaker in calls doesn't work

### ISSUE THREAD

**Issue by sultan2304** [shakalaca/android_device_asus_ze520kl#8]
There is no sound in calls if you wanna turn on the speaker voice. Do you know how to fix it?

**Comment by shakalaca** [comment]
open /system/etc/mixer_paths_mtp.xml and change "voicemmode1-call voice-speaker" to "voicemmode1-call speaker"

but I'm not sure if that's the right solution

**Comment by r18duarte** [comment]
it doesn't fix anything the only thing that it did was putting my phone into a bootloop

**Comment by shakalaca** [comment]
I'll prepare another build for testing .. :)
